name             'ocserv'
maintainer       'ConvergeOne Holding Corp.'
maintainer_email 'C1C_rnd@convergeone.com'
license          'Apache v2.0'
description      'Installs/Configures OpenConnect VPN Server'
long_description 'Installs/Configures OpenConnect VPN Server on CentOS 6.x/7.x'
version          '0.1.0'
issues_url       'https://bitbucket.org/c1c_rnd/ocserv-cookbook/issues'
source_url       'https://bitbucket.org/c1c_rnd/ocserv-cookbook/src'
depends          'firewalld'
depends          'line'
depends          'simple_iptables'
depends          'yum'
supports         'rhel', '>= 6.8', '< 8.0'
