name             'ocserv'
maintainer       'ConvergeOne Collaboration'
maintainer_email 'C1C_rnd@converge-one.com'
license          'All rights reserved'
description      'Installs/Configures OpenConnect VPN'
long_description 'Installs/Configures OpenConnect VPN'
version          '0.1.0'
depends          'simple_iptables'
depends          'yum'
